# Generated by Django 5.0.6 on 2024-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/')),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=8)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
